# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [62]:
### [your code here]

import numpy as np



### 2. Print the NUMPY version and the configuration.


In [63]:
### [your code here]
print(np.__version__)
print(np.show_config())

2.4.6
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.31
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.31
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/Users/ec2-user/croot/numpy_and_nump

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [64]:
### [your code here]

a = np.random.random((2, 3, 5))



### 4. Print a.


In [65]:
### [your code here]
a

array([[[0.30150138, 0.54212387, 0.73797332, 0.69183096, 0.5859538 ],
        [0.63518963, 0.49998741, 0.47173882, 0.51300294, 0.96901465],
        [0.30286156, 0.38273265, 0.48696586, 0.64834952, 0.03979164]],

       [[0.42039778, 0.00898968, 0.27172138, 0.16814059, 0.79263815],
        [0.97616928, 0.88854814, 0.97044504, 0.95792217, 0.67608701],
        [0.26642751, 0.44502492, 0.76457801, 0.28494531, 0.61054197]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [66]:
### [your code here]

b = np.ones((5, 2, 3))


### 6. Print b.


In [67]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [68]:
### [your code here]

equal_result = (a.size == b.size)
print(equal_result)

True



### 8. Are you able to add a and b? Why or why not?


In [69]:
### [your code here]

np.add(a, b)
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [70]:
### [your code here]

c = np.transpose(b, (1, 2, 0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [71]:
print(c.shape)
print(c.shape == a.shape)

(2, 3, 5)
True



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [72]:
### [your code here]

d = np.add(a, c)


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [73]:
### [your code here]

print(a)
print("\n")
print(d)

[[[0.30150138 0.54212387 0.73797332 0.69183096 0.5859538 ]
  [0.63518963 0.49998741 0.47173882 0.51300294 0.96901465]
  [0.30286156 0.38273265 0.48696586 0.64834952 0.03979164]]

 [[0.42039778 0.00898968 0.27172138 0.16814059 0.79263815]
  [0.97616928 0.88854814 0.97044504 0.95792217 0.67608701]
  [0.26642751 0.44502492 0.76457801 0.28494531 0.61054197]]]


[[[1.30150138 1.54212387 1.73797332 1.69183096 1.5859538 ]
  [1.63518963 1.49998741 1.47173882 1.51300294 1.96901465]
  [1.30286156 1.38273265 1.48696586 1.64834952 1.03979164]]

 [[1.42039778 1.00898968 1.27172138 1.16814059 1.79263815]
  [1.97616928 1.88854814 1.97044504 1.95792217 1.67608701]
  [1.26642751 1.44502492 1.76457801 1.28494531 1.61054197]]]



### 12. Multiply a and c. Assign the result to e.


In [74]:
### [your code here]

e = a * c
e

array([[[0.30150138, 0.54212387, 0.73797332, 0.69183096, 0.5859538 ],
        [0.63518963, 0.49998741, 0.47173882, 0.51300294, 0.96901465],
        [0.30286156, 0.38273265, 0.48696586, 0.64834952, 0.03979164]],

       [[0.42039778, 0.00898968, 0.27172138, 0.16814059, 0.79263815],
        [0.97616928, 0.88854814, 0.97044504, 0.95792217, 0.67608701],
        [0.26642751, 0.44502492, 0.76457801, 0.28494531, 0.61054197]]])



### 13. Does e equal to a? Why or why not?


In [75]:
### [your code here]

equal_result = (e == a)
print(equal_result)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [76]:
### [your code here]

d_max = np.max(d); print("Max Value:", d_max)
d_min = np.min(d); print("Min Value:", d_min)
d_mean = np.mean(d); print("Mean of Values:", d_mean)

Max Value: 1.976169279806832
Min Value: 1.0089896809616552
Mean of Values: 1.5437198319127399



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [77]:
### [your code here]

f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [78]:
### [your code here]

conditions = [
    d == d_min,
    d == d_max,
    d == d_mean,
    (d > d_min) & (d < d_mean) ,
    (d > d_mean) & (d < d_max) ,
]

assign_values = [0, 25, 50, 75, 100]

f = np.select(conditions, assign_values)
f

array([[[ 75,  75, 100, 100, 100],
        [100,  75,  75,  75, 100],
        [ 75,  75,  75, 100,  75]],

       [[ 75,   0,  75,  75, 100],
        [ 25, 100, 100, 100, 100],
        [ 75,  75, 100,  75, 100]]])

In [81]:
"""
Alternatives:

Jovana:
for i, value in np.ndenumerate(d):
    if value == d_min:
        f[i] = 0
    elif value == d_max:
        f[i] = 100
    elif value == d_mean:
        f[i] = 50
    elif d_min < value < d_mean:
        f[i] = 25
    elif d_mean < value < d_max:
        f[i] = 75

Gabriel:
d_dims = d.shape

for i in range(d_dims[0]):
    for j in range(d_dims[1]):
        for k in range(d_dims[2]):
            if d[i,j,k] == d_max:
                f[i,j,k] = 100
            elif d_mean < d[i, j, k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i,j,k] = 25
            else:
                f[i,j,k] = 0
"""

'\nAlternatives:\n\nJovana:\nfor i, value in np.ndenumerate(d):\n    if value == d_min:\n        f[i] = 0\n    elif value == d_max:\n        f[i] = 100\n    elif value == d_mean:\n        f[i] = 50\n    elif d_min < value < d_mean:\n        f[i] = 25\n    elif d_mean < value < d_max:\n        f[i] = 75\n\nGabriel:\nd_dims = d.shape\n\nfor i in range(d_dims[0]):\n    for j in range(d_dims[1]):\n        for k in range(d_dims[2]):\n            if d[i,j,k] == d_max:\n                f[i,j,k] = 100\n            elif d_mean < d[i, j, k] < d_max:\n                f[i,j,k] = 75\n            elif d[i,j,k] == d_mean:\n                f[i,j,k] = 50\n            elif d_min < d[i, j, k] < d_mean:\n                f[i,j,k] = 25\n            else:\n                f[i,j,k] = 0\n'





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [79]:
### [your code here]
print(d)
print(f)

[[[1.30150138 1.54212387 1.73797332 1.69183096 1.5859538 ]
  [1.63518963 1.49998741 1.47173882 1.51300294 1.96901465]
  [1.30286156 1.38273265 1.48696586 1.64834952 1.03979164]]

 [[1.42039778 1.00898968 1.27172138 1.16814059 1.79263815]
  [1.97616928 1.88854814 1.97044504 1.95792217 1.67608701]
  [1.26642751 1.44502492 1.76457801 1.28494531 1.61054197]]]
[[[ 75  75 100 100 100]
  [100  75  75  75 100]
  [ 75  75  75 100  75]]

 [[ 75   0  75  75 100]
  [ 25 100 100 100 100]
  [ 75  75 100  75 100]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [86]:
g = np.empty(d.shape, dtype='<U1')   # 1-character string array, same shape as d

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i, j, k]
            if val == d_min:
                g[i, j, k] = 'A'
            elif val == d_max:
                g[i, j, k] = 'E'
            elif val == d_mean:
                g[i, j, k] = 'C'
            elif d_min < val < d_mean:
                g[i, j, k] = 'B'
            elif d_mean < val < d_max:
                g[i, j, k] = 'D'

g


array([[['B', 'B', 'D', 'D', 'D'],
        ['D', 'B', 'B', 'B', 'D'],
        ['B', 'B', 'B', 'D', 'B']],

       [['B', 'A', 'B', 'B', 'D'],
        ['E', 'D', 'D', 'D', 'D'],
        ['B', 'B', 'D', 'B', 'D']]], dtype='<U1')